apiVersion: apps/v1
kind: Deployment
metadata:
 name: tfs-server

spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: tfs-server
    spec:
      containers:
      - image: gcr.io/gcp-ml-172005/tfs-resnet-cpu-opt:latest
        name: tfs-k8s
        imagePullPolicy: Always
        args: ["--tensorflow_inter_op_parallelism=8", "--tensorflow_intra_op_parallelism=4"]
        ports:
        - containerPort: 8500
          name: grpc
        - containerPort: 8501
          name: restapi
        resources: {}