apiVersion: apps/v1
kind: Deployment
metadata:
 name: fastapi-server

spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: fastapi-server
    spec:
      containers:
      - image: gcr.io/gcp-ml-172005/k8s-fastapi:gunicorn-w-17
        name: fastapi-k8s
        imagePullPolicy: Always
        ports:
        - containerPort: 80          
        resources: {}
