apiVersion: apps/v1
kind: Deployment
metadata:
 name: tfs-server

spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: tfs-server
    spec:
      containers:
      - image: gcr.io/gcp-ml-172005/tfs-resnet-cpu-opt:latest
        name: tfs-k8s
        imagePullPolicy: Always
        args: ["--tensorflow_inter_op_parallelism=8", "--tensorflow_intra_op_parallelism=8", "--enable_batching=true", "--batching_parameters_file=/etc/tfs-config/batching_config.txt"]
        ports:
        - containerPort: 8500
          name: grpc
        - containerPort: 8501
          name: restapi
        volumeMounts:
          - mountPath: /etc/tfs-config/batching_config.txt
            subPath: batching_config.txt
            name: tfs-config    
        resources: {}
      volumes:
        - name: tfs-config
          configMap:
            name: tfs-config
